export const AsciiDragon = `                                                :::.....                                                                                                                                                                                                                        
                                              ;:::::::...:                                                                                                                                                                                                                      
                                         ;;X$$$$X;:;;::::.:      ::::            ;                                                                                                                                                                                              
                                        ;;;+XX$$$$$    :::::    ..:::            ::                                                                                                                                                                                             
                                        ++;;;xxx$XX$     :::: :..:              :..                                                                                                                                                                                             
                                        .:++;;..;XXX$     :::::::              :...;                                                                                                                                                                                            
                                       :.:.:;+;..:XX$X     :::::              ....:                                                                                                                                                                                             
                               $XXXX$     .: :++..:+X$XX    XXXX$           :...:::                                                                                                                                                                                             
                             XXXXXXXXX$  ..   :;+..:+XXXXXxxxXXXXX$$$$x+;::...::::                                                                                                                                                                                              
                             $    XXXXXX        :::::;;++xxxXXXXXXXXXXxx+x+:::::                                                                                                                                                                                                
                                   XXXXXXX        ::::++xxXX+xx+++xXXXx++++XX++                                                                                                                                                                                                 
                                  Xxxx+;xXXXXXXXXXX+::;+;;xXx:;++++xXXxx++xxXXXX                                                                                                                                                                                                
                                 +++;;.+XXXXXXXX$$$X::;+;::;++:+.+:+XXXXxxxXXXXXX                                                                                                                                                                                               
                                ;++;+;;;;;;;;;+;;;++.:::::;;;;+++;::+XXXXXXXXXXXXX                                                                                                                                                                                              
                                ;;x++;+;+++++++++++;..::;;;+;;;;XXXX;X$XXXXXXXXXXXX$$XX                                                                                                                                                                                         
                                 ;++X;X+x++x+++;+;+:..;;;;+;;;;;:;x$$$$$$XX$$$$$XXXXXXX                                                                                                                                                                                         
                                 ;;;;;::;:;::+;+;;: .:;;;+;;;;:;;;+X$$$$$$$$$$$$$$XXX                                                                                                                                                                                           
                                   ;;;;;;; ;    :...::;;;:;;:;:::::::;+X$$$$$$$$$$XX$                                           +                                                                                                                                               
                                              :..::: ;::::..:::;;;:::::::;+xX$$$$$$XXXXX$     ;;                       ;:;   +;;;      ;;;;                                                                                                                                     
                                             :.:::    ; :::...:::;;;;::::::..::;;;++;::......:::                ::;  ;:::; ;;:::;   ;;;;;;    +++                                                                                                                               
                                             .::         :;;:..:::::;;;;;;;::................:                ::::; ;::::::::::;:;;;;;;;;;;;;;;;;;;                                                                                                                             
                                             :::::      ++;;;;:..;+;;xx+;++$$$xx+++++;::::               +;   :::::::::;;+++x+++x+++;;;;;;;;;;;;;;                                                                                                                              
                                              :...::;+;;;;;++++x++X$X$$$x++$$$$$$XXXXX                  ;;;; ;:::;;;+xXXXXXXXXXXXXXXXXXX+++;;;;;;;;;;;;;;;                                                                                                                      
                                                ;;;;;;;;++xX$$$$$$$$$$$$$$$$$$$$$XXXXXX                +;;;;;;;;+X$XXXXXXXXXXXXXXXXXXXXXXXXXXx+;;;;;;;;;;;                                                                                                                      
                                              ;;;;;;;++xX$$$$$$$$$$$$$$$$$$$$XX$XXXXXXXX          ;;;  ;;;;;;+X$$$$XXXXXXXXXXXXXXXXXXXxXxXxXXXXXX+;;;;;;                                                                                                                        
                                           +;;;;;;+++X$$$$$$$$$$$$$$$$$$$$x+;;;+XXXXXXXXX         ;;;;;;;;+$$$$$$$$$XXXXXXXXXXXXXXXXXXXXXXXxXXXXXXXx+;;;;;;++                                                                                                                   
                                          ;;;;;;++X$$$$$$$$$$$$$$$$$$X+++;;;;;;;;XXXXXXXXX   ;   ;;;;;;;+$$$$$$$$$$XXXXXXXXXXXXXXXXXXXXxXxXXXXXXXXXXXX+;;;;;;;;;;                                                                                                               
                                        +;;;;;++X$$$$$$$$$$$$$$$Xx++;;;;;;;  ;;;  XXXXXXXXXX;:;  ;:;;+X$$$$$$$$$$$X$XXXXXXXXXXXXXXXXXXXXXXxXXXXXXXXXXXXX+;;;;;;;                                                                                                                
                                      ;;;;;;;+XX$X$$$$$$$$$$Xx+;;;;;  ;::;          XXXXX$XX+;:;::;x$$$$$$$$$$$$XXXXXXXXXXXXXXXXXXXXXXxXxXXXxXXXXXXXXXXXX+;;;+                                                                                                                  
                                     ;:;;;;;xXXXXXXXX$X$$x+;;;;;;;;    ;:            XXXXXX::;::;xXXXXXXX$XXXXXXXXXXXXXXx+++++++++++++xXXXXxXXXXXXXXXXXXXX$+;;;;;;+                                                                                                             
                 ++                +:;;::;;XXXXXXXXXXXX+;;;;;   ;;                    ;+XXX;::;xXXXXXXXXXXXXXXXXXXXXX+++;;;;;;;;;;;;;;;+++xXXXXXXXXXXXXXXX$X+;;;;;;;;    $$                                                                                                     
       +;;:::;+$ ;;:;;            ;;;:::;;xXXXXXXXXXX+;;;;;;                         ;:::;xXxxXXXXXXXXXXXXXXXXXXXX++;;;;;;;;;;;;;;;;;;;;;;;+xxXXXXXXXXXXXXX$$x;;;;;;;     XX                                                                                                    
     ;;::::;;+x$$ ;::;+          +;;::;;;XXXXXXXXXX+;;;;$X;                          ;::::;xXXXXXXXXXXXXXXXXXXx++;;;;;;;;;;;;;:;;:;;::;::;::;++xXXXXXXXXXX$$$$x;;;+        $X $     $$                                                                                          
     +++++XXX$$$$  ;;+++         ;:;;;:;xXXxXXXXXX+;;;;; XX                      ;  ;;;;;+XXXXXXXXXXXXXXXXXx++;;;;;;;;;;;;:;;::;::;::;:::;::;::;+XXXXXXXX$$$$$$X;;;;;;+;   X$X$$  XXX              +;       +;                                                                  
        $ $$$$$$$$$$XXX$        ;;;;;;;+XxXXXXXXX+;;;;;   XX $X      $          ;;;+;;;+XXXXXXXXXXXXXXXXxx+;;;;;;;;;:;;::;:;::;::;::;:::;::;:::;:;xXXXXX$$$$$$$$X;;;;;;;;; X$X$XXX$X             +:::+   ;:::;                                                                  
  +;;::;x$$$$$$$$$$$$$$$        ;;;;;:;XXXXXXXXXx;;;      X$X XX    X$         ;;;;;;+XXXXXXXXXXXXXXXXx+;;;;;;;;:;;;:;::;:;:::;;;+;;;:;;:;;:::;:::;+XXX$$$$$$$$$$X;;;;;;;; X$$XXXX$$      ;;;   ;::::++;:::::;    +;;:;;                                                        
 ;:::;;++$$$$$$$$$$$$$X        ;;;;;;;+XXXXXXXXX+;;;;     XX$XX$$$X$X     ;;;  ;;;;+XXXXXXXXXXXXXXXXx+;;;;;;;::;:::;:;;;+               ;::;;::::;::;X$$$$$$$$$$$$X;;;X$XXXX$$XX$$X$     ;;;; ;::::::::::::;;;;;;;;::;;                                                         
+;;++++x$$$$$$$$$$XXX$         ;;;;;;;xXXXXXXXXX;;;::+    $XXX$$X$$X$    +;;;;;;;+XXXXXxXXXXXxXXxX++;;;;;;;:;::;;:;:;                     ;::::;::::;;x$$$$$$$$$$$$$+;;;;;;+X$XX$X$X$$ ;;;;;;;:;;;;+++x++xxxx++;;;;;;;;+;++++++                                                 
          $$$$$$XXXXX         ;;;;;;;;xXXXXXXXXX;;;;;;     XX$X$XXX$$    ;;;;;;+XXXXXXXXXxXxXXxx+;;;;;;;:;;:;;:;++                   x+    +;:::::;:::;x$$$$$$$$$$$$$+;;;;;XXXX$$$$XXX;;;;;;;;++xXXXXXXXXXXXXXX$$$$Xx+;;;:::::;                                                 
            $$$XXXXXX$        ;;;;;;;;XXXXXXXXXX;;XXXXXXXXXXXXX$$XX$$+   ;;;;+XXXXXXXXXXXXXXXx++;;;;;;;;::;:;;+            +;;:::;;  +;:;;+  ;;;;::::;::+X$$$$$$$$$$$$X+;;+XXXX$$$$;X+;;;+++XXXXXxXXXXXXXXXXXXXXX$$$$$$X+;;::;                                                  
              XXXXXXXXXXX$     ;;;;;;;xXXXXXXXXX;;;;xXXXXxXXXX$$X$X+X;;;;;;+XXXXXXXXXXXXXXXX++;;;;;;;::;;:;              ;;;::::;;+$$ +::;;+  ;;:;;;::::;;X$$$$$$$$$$$$$$xxxXXX$$$Xx$XX$$$XXXXXXXXXXXXXXXXXXXXXXXXX$$$$$$$+;;:;;;++                                             
        ;;     XXXXXXxXXXXX$$$$;;;;;;;xXXXXXXXXX+;;;;;xxxXXXXXX$$$X+$;;;;+XXXXXXXXXXXXXXXX++;;;;;;;:;::;;                ++x+;xXX$$$$$ ;:;++   $x:::::;:::;x$$$$$$$$$$$$$XxxXXXX$$$X$$$$$$XXXXXXXXXXxXXxXXXXXXXXXXXXX$$$$$$$+;:::::::;;                                         
        ;:;;+;XXXXXXXXXxXXX$$$$x;;;;;;+X$$XXXXXXx+;;;;;XXXxXXXX$$$xXX+;+X$$X$XXXXXXXXXXX++;;;;;;;;;:;;;                        $$$$$$$ XxxxX$ X$$X;;:::::;::+$$$$$$$$$$$XXXxxXXX$$$$$$$$$$$$XXXXXXXXx+++++++++++xXXXXXXX$$X$$X;::::::;;                                         
         ;::;++xXXX$$XXXXXX$$$$;;;;;;;;X$$$$XXXXX+;;;;XXXXxxXXXX$XX$X+X$$$$$$$X$XXXXXXx+;;;;;;;;::;:;                 +;;;:;+$$$$$$$$$XXXXXX  X$$$$+;;;::::;:;X$$$$$$$$XXXxXxXXXX$$X$$$$$$$$$XXX++++;+;;;;;;;;;;;;++XXXXXXX$X$$+:::+                                            
          +;;;+XXX      XXX$$$$X;;;;;;;+$$$$XXXXXXX+;+;+xxxxXXXX$$$$X$$$$$$$$$$$$$XX++;;;;;;;;;;;;;                  ;::::;;+X$$$$$$XXXXXXX  XXX$$$$X::::;;::;;x$$$$$$$XXXXxxxXXX$X$$$$$$$$Xx++;;;;;;;;;;;;;;;;;;;;;;+XXXXXXXXXXx::::;;;                                        
               X          X$$$$$;;;;;;;;+$$$XXXXXXXXXXXxXXxxxXXX$$$X$$$$$$$$$$$$$X++;;;;;;;;;;:;+                    +;+++++X$$$$$$XXXXXXX   XXX$$$$$$$::::;;;:;;X$$$$$XXXXxxXXXX$$$$$$$$X++;;;;;;;;;;;;+ + + +;;;;;;;;xXXXXXXXXXX;:::::;;                                      
                            $$$$X;;;;;;::xXXXXXXXXXXXXXXXXXxxXXXX$$$$$$$$$$$$$$x++;;;;;;;;;;;;;;                             $$$$$$XXXXXX    XXXX$$$$$$x;;;::;;;;;+X$$$XXXxXX$$$$$$$$$$X++;;;;;;;;+                ;;;;;+xXXXXXXXXX;:::::;;                                     
                              $$$$;;;:::;:+XXXXXXXXXXXXXXXxXxXXX$$$$$$$$$$$$X++;;;;;;;;;;;;;;                                    $XXXXXXXX  $XXXX$$$$$$$$+;;;;;;;;;;+X$$XXX$$$$$$$$$$$$$$+;;;;;;                     ;;;;;xXXXXXXXXX;::;+                        ;   ;          
                                $$x;;;;::::;+XXXXXXXXXXXXXXXX$$$$$$$$$$$$X++;;;;;;;;;;;;;;                                        XXXXXXXXXXXXXXX$$$$$$$$$$+;;;;;;;;;;+XXX$$$$$$$$$$$$$$$$X;;                          ;;;;+XXXXXXXXX;:;;;;;;;;              ;; +;; ;;+ ;;      
                                   ;::::;::::;+xXXXXXXXXXXXXXXXX$$$$$$$$$$$+;;;;;;;;;;;;                                    ++      XXXX$$XXXxXXX$$$$$$$$$$$x;;;;;;;;;;;+X$$$$$$$$$$$$$$$$$$                            ;;;;+XXXXXXXXX;;;;;;;;;;             ;;;;;;;;;;;;  ;;;  
                                    ;;::::;::::;;;++xxxxXXXXXXXXXXX$$$$$$$$$+;;;;;;;;+                                      ;:;+++xXXXXX$$XXXXXXX$$$$         ;;;;;;;;;;;+XXXXXXXXXXX$$$$$$$                             +;;;+xXXXXXXXx;;;;;;;;             ;;;;::::;;:;;;;;;   
                                      ;;;:::;::;::;;;;;;++XXXXXXXXXXX$$$$$$$X;;;;;+;                                         ;::;++xXXXX$$XXXXXX$$$             ;;;;;;;;;;;+XXXXXXXXXXXX$$$$$                              ;;;;xXXXXXXXx;;;;;;;;;;;   ;;;xxxXXXXX+::::;;;;;;    
                                       ;::;;::;:::;:;;;;;;;+xXXXXXXXXXX$$$$$$+;;;                                             ;;;;;xXXX      XXX$$                 ;;;;;;;;;;++xXXxXXXXXXX$$$                               ;;;;xxXXXxXXX;;;;;;;;;;+;;;;+xXXXXXX$$x:::::;;+ ++;+
                                         +;:;;:::;:;;;;;;;;;;+xxXXXXXXXXX$$$$$                                                     X$                                  ++  ;  + $XXXXXXXXXX$$                                ;;;;+xXXXXXXXx++;;;;;;;;+;xXXXXXXXX$$X;::;;:;;;;;; 
                                             ;:;;:;;;;;;;;;;;;;;++xXXXXXXXX$$$                                                                                                     XXXXxXXXXX                                 ;;;;+xxXXXXXXXXXXx+++++xXXXXXx;XXXXX;::;::;;;;;   
                                                ;;;;;;;;;;;;;;;;;;;;XXXXXXXXX$                                                                                               ;;:;;;X$XXXXxXXX                                   +;;;++xXxXxXXXXXXXXXXXXXx+;:::;;;;:::::;;;;+++  
                                                                 ++x  XXXXXXXXX                                                                                             +;;;;+x$$X$$XXXXXX    $$$$                            ;;;++++xxXXXXXXXXXxx++++:::::::;::;;;;;;;;;;  
                                                               ;;::;+XXX XXXXXX$    $$$$X                                                                                       +XXX$$XXXXXxXXX $$$$$$$+                             +;;;+++++++x++++;;   ::;::;::;:;;;;;+      
                                                              +++++xXXXXXXXXXXXXX $$$$$$X+                                                                                   +;;;xXXXXXXXXXXXXXX$$$$$$+;;                                  +;;;;;;;       ;; ;;;;;;;  ++++      
                                                                 x+XXXXXXXXXXxXXXX$$$$$$+;:                                                                                ;;;;;;+XXXXXXXXXxXXXX$$$$$X+;:;                                                 ;+ ;;  +;;           
                                                               ;:::+XXXXXXXXXXXXXXXX$$$X+;:;                                                                               ;;+++++XXXXXXXXXXXXXXX$     +;;                                                                      
                                                             +;;;+++XXX$$$XXXXXxXXX$      ;;x                                                                                     XXXXXXxXxXXXX          ;                                                                      
                                                             ++x    $XXX$$$$XXXXXX                                                                                               ;;xXXXXXXXXX                                                                                   
                                                                    xXXXX$$$$XXX                                                                                                +:;+XXX$                                                                                        
                                                                   ;;;xXXX$                                                                                                     ;:;++$                                                                                          
                                                                   ;:;+XX                                                                                                       +;;                                                                                             
                                                                   ;;;                                                                                                                                                                                                          
                                                                   +;                                                                                                                                                                                                           `;
export const AsciiDragonSmall = `                #+::..                                                                              
              :==*# :::..    ..                                                                     
           %#%..=:-##++*   ...:                                                                     
          %%##*= *:-+*****++=:                                                                      
            ++=++++:--=--#**##                                                                      
            =++===-.-+==+#######                                                                    
             -=  .::-::----+*****-.      - --------                                                 
                .:.===-:-==*+==:...   --:---=====-----                                              
                +===+*%%%%%%####%   - --=*###******++=-=-                                           
              --==#%%%%#=+=--=####---=*%%#####*********=-=-                                         
             ---*###+==-- -    **+-=#######*+====++****##=---                                       
  ==*#+-=   ---***+===         --+**###*+==---------+*####=-- %## %                                 
---#%%%%#  =--+***-- ###%# - -==*****+=-------:-----:-*#%%%+=-=###  --------=-:                     
= =#%%##   --=***+-- *###% -==*****+=------   -- -=----+%%%%*==###+--==+***+++=---                  
   = #***#%=-=###+--**###+==*##**+=----     =-+##-=++---=#%%%%**######******####+-:--               
   --+##**%+--+###==+**##*#%###+=----      -:=%%%#*##%=---*%%#**##%%%*+===---=+###-:--              
          %%=--*####***##%%%*+==----         %#%#*##*%%#---=*#*#%%%#+=--     --=*##=--        - =   
            #---=+****##%%%#===--            =-+*#%**%%##=====####%%%          -=+**=---    =------ 
              ------=+***#%%*-                --*# *##     ---==+***%#          --+**+====-=*##-----
                ------==+**##                                  -:=#**#            -=+***++**-=+---- 
                       ==****##%#                              +-*##**#%%=          ==+++== -----=  
                      --=###**##+-                             ==*****## =-                         
                         +#%##                                   -###                               
                        --                                       =                                  `;
